baseurl                 = "https://niku.page/"
DefaultContentLanguage  = "en"
title                   = "ニク"
theme                   = "hugo-notepadium"
paginate                = 8
disqusShortname         = ""
googleAnalytics = "UA-149589202-1"
pluralizeListTitles     = false
disableLanguages        = [""]


[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  viewMorePostsLink     = "/post/"
  readingTime           = false
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]