baseURL = "https://niku.page/"
languageCode = "en-us"
canonifyurls = true
title = "ニク"
enableEmoji = true
theme = "hugo-vitae"
publishDir = "docs"
googleAnalytics = "UA-149589202-1"

[params]
contentTypeName = "post"
showMenuItems = 30

# Nav.
[[menu.main]]
name = "運営者情報"
url = "/運営者情報/"
weight = 1

[[menu.main]]
name = "プライバシーポリシー"
url = "/プライバシーポリシー/"
weight = 2

[[menu.main]]
name = "お問い合わせ"
url = "/お問い合わせ/"
weight = 3
